---
- name: Install PHP
  block:
    - name: Install PHP and modules
      apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present

  rescue:
    - debug:
        msg: "PHP installation failed."

  always:
    - name: Restart Apache after PHP install
      service:
        name: apache2
        state: restarted

