---
- name: Install and secure MySQL
  block:
    - name: Preseed MySQL root password
      debconf:
        name: "mysql-server"
        question: "{{ item.question }}"
        value: "{{ mysql_root_password }}"
        vtype: "password"
      loop:
        - { question: "mysql-server/root_password" }
        - { question: "mysql-server/root_password_again" }

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Secure MySQL installation (remove anonymous users, test DB)
      shell: |
        mysql -u root -p{{ mysql_root_password }} <<EOF
        DELETE FROM mysql.user WHERE User='';
        DROP DATABASE IF EXISTS test;
        DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
        FLUSH PRIVILEGES;
        EOF
      args:
        warn: false

  rescue:
    - debug:
        msg: "MySQL installation or hardening failed."

  always:
    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started
        enabled: true

