 ---
- name: Configure firewall (UFW)
  block:
    - name: Install UFW
      apt:
        name: ufw
        state: present

    - name: Allow HTTP and HTTPS
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 80
        - 443

    - name: Enable UFW
      ufw:
        state: enabled
        policy: allow

  rescue:
    - debug:
        msg: "Firewall configuration failed."

